version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POqtSKRshJavfUCVuLCGsBKVrlRTACmV
      POSTGRES_HOST: roundhouse.proxy.rlwy.net
      POSTGRES_PORT: 57119
      POSTGRES_DB: railway
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_app
    environment:
      - REDIS_URL=redis://default:asTehmwvXnscMrJEauqwQyfIcDJXuAko@roundhouse.proxy.rlwy.net:53359

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - 7330:8000
    depends_on:
      - db
      - redis
