"""created model of check and check_student

Revision ID: 0fcc6741cdf9
Revises: 44cfc8d48ac0
Create Date: 2024-03-02 19:40:27.861740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcc6741cdf9'
down_revision: Union[str, None] = '44cfc8d48ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CheckStudent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('check_file_path', sa.Text(), nullable=True),
    sa.Column('price_usd', sa.Integer(), nullable=True),
    sa.Column('price_kzt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['Check.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CheckStudent')
    # ### end Alembic commands ###
