"""university_id

Revision ID: 55e0053e743d
Revises: 0fcc6741cdf9
Create Date: 2024-03-03 22:43:50.696691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e0053e743d'
down_revision: Union[str, None] = '0fcc6741cdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Student', sa.Column('university_id', sa.Integer(), nullable=True))
    op.add_column('Student', sa.Column('faculty_id', sa.Integer(), nullable=True))
    op.add_column('Student', sa.Column('iin', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Student', 'Faculty', ['faculty_id'], ['id'])
    op.create_foreign_key(None, 'Student', 'University', ['university_id'], ['id'])
    op.add_column('StudentApplication', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StudentApplication', 'created_at')
    op.drop_constraint(None, 'Student', type_='foreignkey')
    op.drop_constraint(None, 'Student', type_='foreignkey')
    op.drop_column('Student', 'iin')
    op.drop_column('Student', 'faculty_id')
    op.drop_column('Student', 'university_id')
    # ### end Alembic commands ###
