"""on delete cascade

Revision ID: 5f44e21788c9
Revises: e092f1ea392c
Create Date: 2024-03-09 17:09:04.918114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f44e21788c9'
down_revision: Union[str, None] = 'e092f1ea392c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CheckStudent_check_id_fkey', 'CheckStudent', type_='foreignkey')
    op.drop_constraint('CheckStudent_student_id_fkey', 'CheckStudent', type_='foreignkey')
    op.create_foreign_key(None, 'CheckStudent', 'Student', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'CheckStudent', 'Check', ['check_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('City_country_id_fkey', 'City', type_='foreignkey')
    op.create_foreign_key(None, 'City', 'Country', ['country_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Document_part_id_fkey', 'Document', type_='foreignkey')
    op.create_foreign_key(None, 'Document', 'Part', ['part_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('DocumentStudent_document_id_fkey', 'DocumentStudent', type_='foreignkey')
    op.drop_constraint('DocumentStudent_student_id_fkey', 'DocumentStudent', type_='foreignkey')
    op.create_foreign_key(None, 'DocumentStudent', 'Document', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'DocumentStudent', 'Student', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Faculty_university_id_fkey', 'Faculty', type_='foreignkey')
    op.create_foreign_key(None, 'Faculty', 'University', ['university_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Part_country_id_fkey', 'Part', type_='foreignkey')
    op.create_foreign_key(None, 'Part', 'Country', ['country_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('StudentApplication_student_id_fkey', 'StudentApplication', type_='foreignkey')
    op.create_foreign_key(None, 'StudentApplication', 'Student', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('StudentNotification_student_id_fkey', 'StudentNotification', type_='foreignkey')
    op.create_foreign_key(None, 'StudentNotification', 'Student', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('University_city_id_fkey', 'University', type_='foreignkey')
    op.create_foreign_key(None, 'University', 'City', ['city_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'University', type_='foreignkey')
    op.create_foreign_key('University_city_id_fkey', 'University', 'City', ['city_id'], ['id'])
    op.drop_constraint(None, 'StudentNotification', type_='foreignkey')
    op.create_foreign_key('StudentNotification_student_id_fkey', 'StudentNotification', 'Student', ['student_id'], ['id'])
    op.drop_constraint(None, 'StudentApplication', type_='foreignkey')
    op.create_foreign_key('StudentApplication_student_id_fkey', 'StudentApplication', 'Student', ['student_id'], ['id'])
    op.drop_constraint(None, 'Part', type_='foreignkey')
    op.create_foreign_key('Part_country_id_fkey', 'Part', 'Country', ['country_id'], ['id'])
    op.drop_constraint(None, 'Faculty', type_='foreignkey')
    op.create_foreign_key('Faculty_university_id_fkey', 'Faculty', 'University', ['university_id'], ['id'])
    op.drop_constraint(None, 'DocumentStudent', type_='foreignkey')
    op.drop_constraint(None, 'DocumentStudent', type_='foreignkey')
    op.create_foreign_key('DocumentStudent_student_id_fkey', 'DocumentStudent', 'Student', ['student_id'], ['id'])
    op.create_foreign_key('DocumentStudent_document_id_fkey', 'DocumentStudent', 'Document', ['document_id'], ['id'])
    op.drop_constraint(None, 'Document', type_='foreignkey')
    op.create_foreign_key('Document_part_id_fkey', 'Document', 'Part', ['part_id'], ['id'])
    op.drop_constraint(None, 'City', type_='foreignkey')
    op.create_foreign_key('City_country_id_fkey', 'City', 'Country', ['country_id'], ['id'])
    op.drop_constraint(None, 'CheckStudent', type_='foreignkey')
    op.drop_constraint(None, 'CheckStudent', type_='foreignkey')
    op.create_foreign_key('CheckStudent_student_id_fkey', 'CheckStudent', 'Student', ['student_id'], ['id'])
    op.create_foreign_key('CheckStudent_check_id_fkey', 'CheckStudent', 'Check', ['check_id'], ['id'])
    # ### end Alembic commands ###
