"""added to student study_language, contract_date, full_price, paid_price

Revision ID: a39cb70531dc
Revises: bb1e42ed224f
Create Date: 2024-03-09 15:08:04.093013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39cb70531dc'
down_revision: Union[str, None] = 'bb1e42ed224f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Student', sa.Column('contract_date', sa.Date(), nullable=True))
    op.add_column('Student', sa.Column('full_price', sa.Integer(), nullable=True))
    op.add_column('Student', sa.Column('paid_price', sa.Integer(), nullable=True))
    op.add_column('Student', sa.Column('study_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Student', 'study_language')
    op.drop_column('Student', 'paid_price')
    op.drop_column('Student', 'full_price')
    op.drop_column('Student', 'contract_date')
    # ### end Alembic commands ###
