"""contract number

Revision ID: b259f16d410a
Revises: 55e0053e743d
Create Date: 2024-03-03 23:00:19.406409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b259f16d410a'
down_revision: Union[str, None] = '55e0053e743d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Student', sa.Column('contract_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Student', 'contract_number')
    # ### end Alembic commands ###
