"""document, part

Revision ID: be473f3ce189
Revises: b259f16d410a
Create Date: 2024-03-04 12:40:21.804728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be473f3ce189'
down_revision: Union[str, None] = 'b259f16d410a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Document', 'underage')
    op.drop_column('Document', 'moderator')
    op.add_column('Part', sa.Column('underage', sa.Boolean(), nullable=True))
    op.add_column('Part', sa.Column('moderator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Part', 'moderator')
    op.drop_column('Part', 'underage')
    op.add_column('Document', sa.Column('moderator', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('Document', sa.Column('underage', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
