"""added to student study_language, contract_date, full_price, paid_price

Revision ID: e092f1ea392c
Revises: 6d821336421a
Create Date: 2024-03-09 17:05:21.147967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e092f1ea392c'
down_revision: Union[str, None] = '6d821336421a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('AdminNotification_document_student_id_fkey', 'AdminNotification', type_='foreignkey')
    op.drop_constraint('AdminNotification_student_application_id_fkey', 'AdminNotification', type_='foreignkey')
    op.create_foreign_key(None, 'AdminNotification', 'DocumentStudent', ['document_student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'AdminNotification', 'StudentApplication', ['student_application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'AdminNotification', type_='foreignkey')
    op.drop_constraint(None, 'AdminNotification', type_='foreignkey')
    op.create_foreign_key('AdminNotification_student_application_id_fkey', 'AdminNotification', 'StudentApplication', ['student_application_id'], ['id'])
    op.create_foreign_key('AdminNotification_document_student_id_fkey', 'AdminNotification', 'DocumentStudent', ['document_student_id'], ['id'])
    # ### end Alembic commands ###
