"""changed status to status_id

Revision ID: fe74dd2f0608
Revises: fd8ca1967ae7
Create Date: 2024-03-02 15:05:55.972337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe74dd2f0608'
down_revision: Union[str, None] = 'fd8ca1967ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Student', sa.Column('status_id', sa.Integer(), nullable=True))
    op.drop_constraint('Student_status_fkey', 'Student', type_='foreignkey')
    op.create_foreign_key(None, 'Student', 'Status', ['status_id'], ['id'])
    op.drop_column('Student', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Student', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Student', type_='foreignkey')
    op.create_foreign_key('Student_status_fkey', 'Student', 'Status', ['status'], ['id'])
    op.drop_column('Student', 'status_id')
    # ### end Alembic commands ###
